### ISSUE TITLE
这个例子有小小的问题，转换时报错，我是gin框架

### ISSUE THREAD

**Issue by liuzhongsheng** [azhengyongqin/golang-tree-menu#1]
希望改进改进，调用报错，
```go
func (s SystemMenus) ConvertToINodeArray() (nodes []INode) {
	for _, v := range s {
		nodes = append(nodes, v)
	}
	return
}
```

**Comment by azhengyongqin** [comment]
@liuzhongsheng 这个跟 `gin` 框架没关系， 可以提供下你菜单结构体，跟实现的接口方法吗？

**Comment by liuzhongsheng** [comment]
tree.go和你代码一模一样，然后改动的代码为：`package menu_cate
```go
import (
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/tidwall/pretty"
	"v1/application/util/tree"
	//"testing"
	
)

type SystemMenu struct {
	Id       int    `json:"id"`        //id
	FatherId int    `json:"pid"` //上级菜单id
	Name     string `json:"name"`      //菜单名
}

func (s SystemMenu) GetTitle() string {
	return s.Name
}
func (s SystemMenu) GetId() int {
	return s.Id
}
func (s SystemMenu) GetFatherId() int {
	return s.FatherId
}
func (s SystemMenu) GetData() interface{} {
	return s
}
func (s SystemMenu) IsRoot() bool {
	// 这里通过FatherId等于0 或者 FatherId等于自身Id表示顶层根节点
	return s.FatherId == 0 || s.FatherId == s.Id
}

type SystemMenus []SystemMenu

// ConvertToINodeArray 将当前数组转换成父类 INode 接口 数组
func (s SystemMenus) ConvertToINodeArray() (nodes []INode) {
	for _, v := range s {
		nodes = append(nodes, v)
	}
	return
}



func TestGenerateTree(c *gin.Context) {
	// 模拟获取数据库中所有菜单，在其它所有的查询中，也是首先将数据库中所有数据查询出来放到数组中，
	// 后面的遍历递归，都在这个 allMenu中进行，而不是在数据库中进行递归查询，减小数据库压力。
	allMenu := []SystemMenu{
		{Id: 1, FatherId: 0, Name: "系统总览"},
		{Id: 2, FatherId: 0, Name: "系统配置"},

		{Id: 3, FatherId: 1, Name: "资产"},
		{Id: 4, FatherId: 1, Name: "动环"},

		{Id: 5, FatherId: 2, Name: "菜单配置"},
		{Id: 6, FatherId: 3, Name: "设备"},
		{Id: 7, FatherId: 3, Name: "机柜"},
	}

	// 生成完全树
	resp := tree.GenerateTree(SystemMenus.ConvertToINodeArray(allMenu), nil)
	bytes, _ := json.MarshalIndent(resp, "", "\t")
	//fmt.Println(string(pretty.Color(pretty.PrettyOptions(bytes, pretty.DefaultOptions), nil)))

	// 模拟选中 '资产' 菜单
	selectedNode := []SystemMenu{allMenu[2]}
	resp = tree.GenerateTree(SystemMenus.ConvertToINodeArray(allMenu), SystemMenus.ConvertToINodeArray(selectedNode))
	bytes, _ = json.Marshal(resp)
	//fmt.Println(string(pretty.Color(pretty.PrettyOptions(bytes, pretty.DefaultOptions), nil)))

	// 模拟从数据库中查询出 '设备'
	device := []SystemMenu{allMenu[5]}
	// 查询 设备 的所有父节点
	respNodes := tree.FindRelationNode(SystemMenus.ConvertToINodeArray(device), SystemMenus.ConvertToINodeArray(allMenu))
	resp = tree.GenerateTree(respNodes, nil)
	bytes, _ = json.Marshal(resp)
	fmt.Println(string(pretty.Color(pretty.PrettyOptions(bytes, pretty.DefaultOptions), nil)))
}
```

**Comment by liuzhongsheng** [comment]
> @liuzhongsheng 这个跟 `gin` 框架没关系， 可以提供下你菜单结构体，跟实现的接口方法吗？

基本没做改动，带码是我刚刚提交那个，只是改了`type SystemMenu struct {
	Id       int    `json:"id"`        //id
	FatherId int    `json:"pid"` //上级菜单id
	Name     string `json:"name"`      //菜单名
}
`

**Comment by azhengyongqin** [comment]
@liuzhongsheng 我试了你的代码，那个方法是没问题的，可以看看你的报错信息吗？
![image](https://user-images.githubusercontent.com/18138282/67356029-86108680-f58b-11e9-905d-046767e9321f.png)

**Comment by liuzhongsheng** [comment]
> @liuzhongsheng 我试了你的代码，那个方法是没问题的，可以看看你的报错信息吗？
> ![image](https://user-images.githubusercontent.com/18138282/67356029-86108680-f58b-11e9-905d-046767e9321f.png)

错误信息为：menu_cate.go:39:53: undefined: INode

**Comment by azhengyongqin** [comment]
@liuzhongsheng 那是你的包引入问题，不是代码问题

**Comment by liuzhongsheng** [comment]
> @liuzhongsheng 那是你的包引入问题，不是代码问题

包用直接引的不行，用下载的也不行

**Comment by liuzhongsheng** [comment]
> @liuzhongsheng 那是你的包引入问题，不是代码问题

除了那两个文件的代码，没有其他代码了

**Comment by azhengyongqin** [comment]
@liuzhongsheng 对就这两个文件， 你可以用这种方式引入
![image](https://user-images.githubusercontent.com/18138282/67357264-51063300-f58f-11e9-807c-afe1093e9195.png)

**Comment by liuzhongsheng** [comment]
> @liuzhongsheng 对就这两个文件， 你可以用这种方式引入
> ![image](https://user-images.githubusercontent.com/18138282/67357264-51063300-f58f-11e9-807c-afe1093e9195.png)
一样不行

**Comment by azhengyongqin** [comment]
@liuzhongsheng 先在命令行中执行`go get https://github.com/azhengyongqin/golang-tree-menu`

**Comment by liuzhongsheng** [comment]
> @liuzhongsheng 先在命令行中执行`go get https://github.com/azhengyongqin/golang-tree-menu`
我是用的go mod，我看了下已经加载进去了，会不会和我系统有关

**Comment by liuzhongsheng** [comment]
问题已经解决，你的演示有问题，多谢你的代码不过你演示代码应该调整为更合适
`package menu_cate

import (
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/tidwall/pretty"
	tree "github.com/azhengyongqin/golang-tree-menu"
)

// 定义我们自己的菜单对象
type SystemMenu struct {
	Id       int    `json:"id"`        //id
	FatherId int    `json:"father_id"` //上级菜单id
	Name     string `json:"name"`      //菜单名
	Route    string `json:"route"`     //页面路径
	Icon     string `json:"icon"`      //图标路径
}

// region 实现ITree 所有接口
func (s SystemMenu) GetTitle() string {
	return s.Name
}

func (s SystemMenu) GetId() int {
	return s.Id
}

func (s SystemMenu) GetFatherId() int {
	return s.FatherId
}

func (s SystemMenu) GetData() interface{} {
	return s
}

func (s SystemMenu) IsRoot() bool {
	// 这里通过FatherId等于0 或者 FatherId等于自身Id表示顶层根节点
	return s.FatherId == 0 || s.FatherId == s.Id
}

// endregion

type SystemMenus []SystemMenu

// ConvertToINodeArray 将当前数组转换成父类 INode 接口 数组
func (s SystemMenus) ConvertToINodeArray() (nodes []tree.INode) {
	for _, v := range s {
		nodes = append(nodes, v)
	}
	return
}

func TestGenerateTree(c *gin.Context) {
	// 模拟获取数据库中所有菜单，在其它所有的查询中，也是首先将数据库中所有数据查询出来放到数组中，
	// 后面的遍历递归，都在这个 allMenu中进行，而不是在数据库中进行递归查询，减小数据库压力。
	allMenu := []SystemMenu{
		{Id: 1, FatherId: 0, Name: "系统总览", Route: "/systemOverview", Icon: "icon-system"},
		{Id: 2, FatherId: 0, Name: "系统配置", Route: "/systemConfig", Icon: "icon-config"},

		{Id: 3, FatherId: 1, Name: "资产", Route: "/asset", Icon: "icon-asset"},
		{Id: 4, FatherId: 1, Name: "动环", Route: "/pe", Icon: "icon-pe"},

		{Id: 5, FatherId: 2, Name: "菜单配置", Route: "/menuConfig", Icon: "icon-menu-config"},
		{Id: 6, FatherId: 3, Name: "设备", Route: "/device", Icon: "icon-device"},
		{Id: 7, FatherId: 3, Name: "机柜", Route: "/device", Icon: "icon-device"},
	}

	// 生成完全树
	resp := tree.GenerateTree(SystemMenus.ConvertToINodeArray(allMenu), nil)
	bytes, _ := json.MarshalIndent(resp, "", "\t")
	//fmt.Println(string(pretty.Color(pretty.PrettyOptions(bytes, pretty.DefaultOptions), nil)))

	// 模拟选中 '资产' 菜单
	selectedNode := []SystemMenu{allMenu[2]}
	resp = tree.GenerateTree(SystemMenus.ConvertToINodeArray(allMenu), SystemMenus.ConvertToINodeArray(selectedNode))
	bytes, _ = json.Marshal(resp)
	//fmt.Println(string(pretty.Color(pretty.PrettyOptions(bytes, pretty.DefaultOptions), nil)))

	// 模拟从数据库中查询出 '设备'
	device := []SystemMenu{allMenu[5]}
	// 查询 设备 的所有父节点
	respNodes := tree.FindRelationNode(SystemMenus.ConvertToINodeArray(device), SystemMenus.ConvertToINodeArray(allMenu))
	resp = tree.GenerateTree(respNodes, nil)
	bytes, _ = json.Marshal(resp)
	fmt.Println(string(pretty.Color(pretty.PrettyOptions(bytes, pretty.DefaultOptions), nil)))
}

`
